import { Room, Testimonial, Activity } from "@/types";

export const rooms: Room[] = [
  {
    id: "fare-miti",
    name: "Fare Miti",
    nameFr: "Fare Miti",
    slug: "fare-miti",
    description:
      "Our signature overwater bungalow with a private deck overlooking the crystalline lagoon. Wake up to the gentle sound of waves beneath your feet.",
    descriptionFr:
      "Notre bungalow signature sur pilotis avec terrasse privee surplombant le lagon cristallin. Reveillez-vous au doux son des vagues sous vos pieds.",
    capacity: 2,
    price: 35000,
    priceLabel: "35 000 XPF / nuit",
    size: "45 m\u00B2",
    bedType: "King-size bed",
    bedTypeFr: "Lit king-size",
    amenities: [
      "Lagoon view",
      "Private deck",
      "Outdoor shower",
      "Air conditioning",
      "Mini bar",
      "Free WiFi",
      "Kayak access",
      "Snorkeling gear",
    ],
    amenitiesFr: [
      "Vue lagon",
      "Terrasse privee",
      "Douche exterieure",
      "Climatisation",
      "Mini bar",
      "WiFi gratuit",
      "Acces kayak",
      "Equipement snorkeling",
    ],
    images: [
      "/images/povai-chambre-miti.png",
      "/images/povai-chambre-mahana.png",
      "/images/povai-chambre-moana.png",
      "/images/povai-hero.png",
    ],
    featured: true,
  },
  {
    id: "fare-hana",
    name: "Fare Hana",
    nameFr: "Fare Hana",
    slug: "fare-hana",
    description:
      "A lush garden bungalow nestled among tropical flowers and coconut palms, offering serene privacy and authentic Polynesian charm.",
    descriptionFr:
      "Un bungalow jardin luxuriant niché parmi les fleurs tropicales et les cocotiers, offrant une intimite sereine et un charme polynesien authentique.",
    capacity: 3,
    price: 28000,
    priceLabel: "28 000 XPF / nuit",
    size: "38 m\u00B2",
    bedType: "Queen bed + single bed",
    bedTypeFr: "Lit queen + lit simple",
    amenities: [
      "Garden view",
      "Private terrace",
      "Outdoor shower",
      "Air conditioning",
      "Mini fridge",
      "Free WiFi",
      "Bicycle",
      "Hammock",
    ],
    amenitiesFr: [
      "Vue jardin",
      "Terrasse privee",
      "Douche exterieure",
      "Climatisation",
      "Mini frigo",
      "WiFi gratuit",
      "Velo",
      "Hamac",
    ],
    images: [
      "/images/povai-chambre-mahana.png",
      "/images/povai-chambre-miti.png",
      "/images/povai-chambre-moana.png",
      "/images/povai-lodge-ext.png",
    ],
    featured: false,
  },
  {
    id: "fare-maeva",
    name: "Fare Maeva",
    nameFr: "Fare Maeva",
    slug: "fare-maeva",
    description:
      "Our premium suite with panoramic views of Mount Otemanu. A spacious retreat featuring a private plunge pool and outdoor living area.",
    descriptionFr:
      "Notre suite premium avec vue panoramique sur le Mont Otemanu. Un havre spacieux avec piscine privee et espace de vie exterieur.",
    capacity: 4,
    price: 45000,
    priceLabel: "45 000 XPF / nuit",
    size: "60 m\u00B2",
    bedType: "King bed + sofa bed",
    bedTypeFr: "Lit king + canape-lit",
    amenities: [
      "Mountain & lagoon view",
      "Private plunge pool",
      "Outdoor living area",
      "Air conditioning",
      "Full minibar",
      "Free WiFi",
      "Kayak & paddleboard",
      "Premium toiletries",
    ],
    amenitiesFr: [
      "Vue montagne & lagon",
      "Piscine privee",
      "Salon exterieur",
      "Climatisation",
      "Minibar complet",
      "WiFi gratuit",
      "Kayak & paddle",
      "Produits de soin premium",
    ],
    images: [
      "/images/povai-chambre-moana.png",
      "/images/povai-lodge-ext.png",
      "/images/povai-chambre-miti.png",
      "/images/povai-chambre-mahana.png",
    ],
    featured: true,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Sophie & Marc",
    country: "France",
    rating: 5,
    text: "An absolute paradise. The Fare Miti bungalow was beyond our dreams. Waking up above the turquoise lagoon was magical. Christian is the most welcoming host.",
    textFr:
      "Un paradis absolu. Le bungalow Fare Miti a depasse nos reves. Se reveiller au-dessus du lagon turquoise etait magique. Christian est l'hote le plus accueillant.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
    date: "2025-12",
  },
  {
    id: "t2",
    name: "James & Emily",
    country: "Australia",
    rating: 5,
    text: "We've traveled the world but Povai Lodge stands out. The intimacy of just 3 rooms means you feel like you have Bora Bora all to yourself.",
    textFr:
      "Nous avons voyage dans le monde entier mais Povai Lodge se distingue. L'intimite de seulement 3 chambres vous donne l'impression d'avoir Bora Bora pour vous seul.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    date: "2025-11",
  },
  {
    id: "t3",
    name: "Yuki & Takeshi",
    country: "Japan",
    rating: 5,
    text: "Perfect honeymoon destination. The sunset views from Fare Maeva were breathtaking. We will definitely come back.",
    textFr:
      "Destination lune de miel parfaite. Les couchers de soleil depuis Fare Maeva etaient a couper le souffle. Nous reviendrons certainement.",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    date: "2026-01",
  },
  {
    id: "t4",
    name: "Lisa & Tom",
    country: "USA",
    rating: 5,
    text: "Christian's local knowledge made our stay unforgettable. He arranged the best snorkeling spots and a private motu picnic. Pure bliss.",
    textFr:
      "La connaissance locale de Christian a rendu notre sejour inoubliable. Il a organise les meilleurs spots de snorkeling et un pique-nique prive sur un motu. Pur bonheur.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    date: "2026-02",
  },
];

export const activities: Activity[] = [
  {
    id: "a1",
    name: "Lagoon Snorkeling",
    nameFr: "Snorkeling dans le lagon",
    description: "Explore the vibrant coral gardens and swim with tropical fish in crystal-clear waters.",
    descriptionFr: "Explorez les jardins de coraux et nagez avec les poissons tropicaux dans des eaux cristallines.",
    image: "/images/povai-plongee.png",
    duration: "2-3h",
  },
  {
    id: "a2",
    name: "Mount Otemanu Hike",
    nameFr: "Randonnee Mont Otemanu",
    description: "A guided trek through lush vegetation with panoramic views of the island.",
    descriptionFr: "Une randonnee guidee a travers une vegetation luxuriante avec vue panoramique sur l'ile.",
    image: "/images/povai-lodge-ext.png",
    duration: "4-5h",
  },
  {
    id: "a3",
    name: "Sunset Cruise",
    nameFr: "Croisiere au coucher de soleil",
    description: "Sail around the lagoon as the sky transforms into shades of gold and pink.",
    descriptionFr: "Naviguez autour du lagon tandis que le ciel se transforme en nuances d'or et de rose.",
    image: "/images/povai-hero.png",
    duration: "2h",
  },
  {
    id: "a4",
    name: "Motu Picnic",
    nameFr: "Pique-nique sur un motu",
    description: "A private picnic on a deserted islet with fresh local cuisine and pristine beaches.",
    descriptionFr: "Un pique-nique prive sur un ilot desert avec cuisine locale fraiche et plages immaculees.",
    image: "/images/povai-kayak.png",
    duration: "Half day",
  },
  {
    id: "a5",
    name: "Jet Ski Tour",
    nameFr: "Tour en jet ski",
    description: "Explore the island's coastline at high speed with guided jet ski excursions.",
    descriptionFr: "Explorez le littoral de l'ile a grande vitesse avec des excursions en jet ski guidees.",
    image: "/images/povai-kayak.png",
    duration: "1-2h",
  },
  {
    id: "a6",
    name: "Polynesian Cooking",
    nameFr: "Cuisine polynesienne",
    description: "Learn to prepare traditional dishes like poisson cru with fresh local ingredients.",
    descriptionFr: "Apprenez a preparer des plats traditionnels comme le poisson cru avec des ingredients locaux frais.",
    image: "/images/povai-lodge-ext.png",
    duration: "3h",
  },
];

export const translations = {
  fr: {
    nav: {
      home: "Accueil",
      rooms: "Nos Chambres",
      reservation: "Reservation",
      lodge: "Le Lodge",
      contact: "Contact",
    },
    hero: {
      title: "Votre havre de paix a Bora Bora",
      subtitle: "Vivez l'experience authentique de la Polynesie dans notre lodge intime de 3 chambres, niché au coeur du plus beau lagon du monde.",
      cta: "Reserver maintenant",
      discover: "Decouvrir nos chambres",
    },
    rooms: {
      title: "Nos Chambres",
      subtitle: "Trois havres de paix uniques, chacun offrant une experience inoubliable au coeur de Bora Bora.",
      capacity: "Capacite",
      persons: "personnes",
      size: "Surface",
      from: "A partir de",
      perNight: "/ nuit",
      amenities: "Equipements",
      book: "Reserver cette chambre",
      viewAll: "Voir toutes nos chambres",
      gallery: "Galerie photos",
    },
    reservation: {
      title: "Reservez votre sejour",
      subtitle: "Selectionnez votre chambre et vos dates pour vivre une experience inoubliable a Bora Bora.",
      step1: "Chambre",
      step2: "Dates",
      step3: "Informations",
      step4: "Confirmation",
      selectRoom: "Choisissez votre chambre",
      selectDates: "Selectionnez vos dates",
      checkIn: "Arrivee",
      checkOut: "Depart",
      guests: "Nombre de personnes",
      yourInfo: "Vos informations",
      firstName: "Prenom",
      lastName: "Nom",
      email: "Email",
      phone: "Telephone",
      message: "Message (optionnel)",
      messagePlaceholder: "Demandes speciales, heure d'arrivee prevue...",
      next: "Suivant",
      previous: "Precedent",
      confirm: "Confirmer la reservation",
      confirmed: "Reservation confirmee !",
      confirmedText: "Merci pour votre demande de reservation. Christian vous contactera dans les 24h pour confirmer votre sejour.",
      summary: "Recapitulatif",
      newReservation: "Nouvelle reservation",
    },
    lodge: {
      title: "Le Lodge",
      subtitle: "Decouvrez l'histoire de Povai Lodge et la magie de Bora Bora.",
      story: "Notre histoire",
      storyText1: "Povai Lodge est ne de la passion de Christian pour sa terre natale. Apres des annees a voyager, il est revenu a Bora Bora avec une vision : creer un lieu ou les voyageurs pourraient vivre l'authenticite polynesienne.",
      storyText2: "Nos trois chambres d'hotes sont pensees pour offrir une experience intime et personnalisee, loin des grands complexes hoteliers. Ici, vous etes chez vous, au milieu du lagon le plus beau du monde.",
      location: "Localisation",
      locationText: "Situe sur la cote ouest de Bora Bora, Povai Lodge offre des vues imprenables sur le lagon turquoise et le majestueux Mont Otemanu.",
      activities: "Activites aux alentours",
      activitiesText: "Bora Bora regorge d'experiences uniques. Christian vous guidera vers les meilleurs spots et activites de l'ile.",
    },
    contact: {
      title: "Contactez-nous",
      subtitle: "Une question ? N'hesitez pas a nous ecrire ou nous appeler.",
      name: "Nom complet",
      email: "Email",
      phone: "Telephone",
      subject: "Sujet",
      message: "Votre message",
      send: "Envoyer le message",
      sent: "Message envoye !",
      sentText: "Merci pour votre message. Nous vous repondrons dans les plus brefs delais.",
      info: "Informations",
      address: "Bora Bora, Polynesie francaise",
      followUs: "Suivez-nous",
    },
    footer: {
      rights: "Tous droits reserves",
      tagline: "Votre havre de paix a Bora Bora",
    },
    common: {
      whatsapp: "Contactez-nous sur WhatsApp",
    },
  },
  en: {
    nav: {
      home: "Home",
      rooms: "Our Rooms",
      reservation: "Reservation",
      lodge: "The Lodge",
      contact: "Contact",
    },
    hero: {
      title: "Your peaceful retreat in Bora Bora",
      subtitle: "Experience authentic Polynesia in our intimate 3-room lodge, nestled in the heart of the world's most beautiful lagoon.",
      cta: "Book now",
      discover: "Discover our rooms",
    },
    rooms: {
      title: "Our Rooms",
      subtitle: "Three unique peaceful retreats, each offering an unforgettable experience in the heart of Bora Bora.",
      capacity: "Capacity",
      persons: "guests",
      size: "Size",
      from: "From",
      perNight: "/ night",
      amenities: "Amenities",
      book: "Book this room",
      viewAll: "View all our rooms",
      gallery: "Photo gallery",
    },
    reservation: {
      title: "Book your stay",
      subtitle: "Select your room and dates for an unforgettable experience in Bora Bora.",
      step1: "Room",
      step2: "Dates",
      step3: "Information",
      step4: "Confirmation",
      selectRoom: "Choose your room",
      selectDates: "Select your dates",
      checkIn: "Check-in",
      checkOut: "Check-out",
      guests: "Number of guests",
      yourInfo: "Your information",
      firstName: "First name",
      lastName: "Last name",
      email: "Email",
      phone: "Phone",
      message: "Message (optional)",
      messagePlaceholder: "Special requests, expected arrival time...",
      next: "Next",
      previous: "Previous",
      confirm: "Confirm reservation",
      confirmed: "Reservation confirmed!",
      confirmedText: "Thank you for your reservation request. Christian will contact you within 24 hours to confirm your stay.",
      summary: "Summary",
      newReservation: "New reservation",
    },
    lodge: {
      title: "The Lodge",
      subtitle: "Discover the story of Povai Lodge and the magic of Bora Bora.",
      story: "Our story",
      storyText1: "Povai Lodge was born from Christian's passion for his homeland. After years of traveling, he returned to Bora Bora with a vision: create a place where travelers could experience authentic Polynesia.",
      storyText2: "Our three guest rooms are designed to offer an intimate, personalized experience, far from large hotel complexes. Here, you are at home, in the middle of the world's most beautiful lagoon.",
      location: "Location",
      locationText: "Located on the west coast of Bora Bora, Povai Lodge offers stunning views of the turquoise lagoon and the majestic Mount Otemanu.",
      activities: "Nearby activities",
      activitiesText: "Bora Bora is full of unique experiences. Christian will guide you to the best spots and activities on the island.",
    },
    contact: {
      title: "Contact us",
      subtitle: "Have a question? Don't hesitate to write or call us.",
      name: "Full name",
      email: "Email",
      phone: "Phone",
      subject: "Subject",
      message: "Your message",
      send: "Send message",
      sent: "Message sent!",
      sentText: "Thank you for your message. We will get back to you as soon as possible.",
      info: "Information",
      address: "Bora Bora, French Polynesia",
      followUs: "Follow us",
    },
    footer: {
      rights: "All rights reserved",
      tagline: "Your peaceful retreat in Bora Bora",
    },
    common: {
      whatsapp: "Contact us on WhatsApp",
    },
  },
};
