import { NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase';
import { rateLimitAsync, getClientIp } from '@/lib/rate-limit';
import { verifyUnsubscribeToken } from '@/lib/portal-token';

/**
 * POST /api/unsubscribe — opt out of marketing emails
 * Body: { token: string } (HMAC-signed, generated by generateUnsubscribeToken)
 */
export async function POST(req: Request) {
  const ip = getClientIp(req);
  const { success: rlOk } = await rateLimitAsync(`unsub:${ip}`, { interval: 60_000, limit: 10 });
  if (!rlOk) {
    return NextResponse.json({ error: 'Too many requests' }, { status: 429 });
  }

  let body: { token?: string; email?: string };
  try {
    body = (await req.json()) as { token?: string; email?: string };
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }

  // Require signed token — reject raw email
  const token = body.token;
  if (!token) {
    return NextResponse.json({ error: 'Token requis' }, { status: 400 });
  }

  const email = verifyUnsubscribeToken(token);
  if (!email) {
    return NextResponse.json({ error: 'Lien invalide ou expire' }, { status: 403 });
  }

  const supabase = supabaseAdmin();

  // Update business by email (owner email)
  const { error } = await supabase
    .from('bookbot_businesses')
    .update({ marketing_opt_out: true })
    .eq('email', email);

  if (error) {
    return NextResponse.json({ error: 'Erreur interne' }, { status: 500 });
  }

  // Also opt out prospects table
  await supabase
    .from('bookbot_prospects')
    .update({ drip_unsubscribed: true })
    .eq('email', email);

  // Always return success (don't leak whether email exists)
  return NextResponse.json({ success: true });
}
