-- Blog articles table
-- Source of truth for articles generated by the Trigger.dev daily-blog-post workflow.
-- The static lib/blog-data.ts serves as fallback when Supabase is unavailable.

CREATE TABLE IF NOT EXISTS blog_articles (
  slug        TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  description TEXT NOT NULL,
  date        DATE NOT NULL,
  category    TEXT NOT NULL,
  read_time   TEXT NOT NULL DEFAULT '5 min',
  content     TEXT NOT NULL,
  image       TEXT,           -- CSS gradient string, optional
  published   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for the most common query pattern: published articles ordered by date desc
CREATE INDEX IF NOT EXISTS blog_articles_published_date_idx
  ON blog_articles (published, date DESC);

-- Row Level Security: public read on published articles, no write from client
ALTER TABLE blog_articles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read published articles"
  ON blog_articles
  FOR SELECT
  USING (published = TRUE);
